### ISSUE TITLE
Use of undeclared type 'BindableObject'

### ISSUE THREAD

**Issue by 8secz-johndpope** [rayfix/ForceDirectedGraph#2]
<img width="1236" alt="Screen Shot 2020-04-06 at 8 15 03 pm" src="https://user-images.githubusercontent.com/50567111/78547995-50aedb00-7843-11ea-9c67-1176841da5da.png">

**Comment by rayfix** [comment]
Thanks.  I made it work with the latest version of SwiftUI.  @BindableObject was in the SwiftUI beta 😅
